In [2]:
import numpy as np
import statistics as st


# Basics of Linear Algebra and Statistics

## Linear Algebra
### Scaler Vs Vector
When a single quantity is enough to describe something then this quantity is <b>scaler</b>, otherwise when you need more than one describtor you are dealing with <b>vectors</b>.



#### Test your Understanding
<b>Mention if the following quantity is a scaler or vector. And if it was a vectore mention its dimension</b> </br>

<ul>
<li>Weight</li>
<li>Humidity</li>
<li>Velocity</li>
<li>Image</li>
<li>Students Weights</li>
<li>Product prices over a year with defined time step</li>
<li>Product prices over a year with random time step</li>
</ul>

In [4]:
x = np.array([[1,2,3]])
x.shape

(1, 3)

## Getting Vecotr Length
![](./imges/vecLength.jpg)

### Mathematical Operations on Vectors

#### 1- Adding and Subtracting
![image info](./imges/adding.png)


In [3]:
x = np.array([[1,2,3]])
y = np.array([[1,2,3]])

print(x + y)
#What is the difference between this example and the example in the image

[[2 4 6]]


In [5]:
z = x + y
print(z - x)

[[1 2 3]]


#### 2- Vector-Scalar Multiplication
Some times called scalling or weighting. It is a bitwise operation
![image info](./imges/Scaling.png)

In [9]:
alpha = 2
x = np.array([[1],
             [2],
             [3]])

y = np.array([[1, 1],
             [2, 2],
             [3, 3]])


print(x*y)

[[1 1]
 [4 4]
 [9 9]]


#### Test your Understanding
- If a company need an equation to chane employees saleries based on the anual increase. What should be this equation. Write some code please</br>

- Think of examples where vector-scaling is important!

#### 2- Vector-Vector Multiplication (dot-product)
![image info](./imges/dotProduct_1.png)

In [13]:
x = np.array([[1],
             [6],
             [-2]])

y = np.array([[-1],
             [0],
             [0.2]])

print(x.T @ y)

[[-1.4]]


##### dot-product and cosine similarity
Another formula to calculate the dot product is to multiply the length of the first vector by the length of the second vector by the cosine angle between the two vectors.</br>
![image info](./imges/dotProduct_2.png)<br>

cosine values ranges between one and zero
- cos(0) = cos(180) = 1
- cos(90) = 0 </br>
For this conclusion the cosine value for the angle between two vectors became a very important measurement for the similarity of two vectors

#### Matrix-Matrix Multiplication
- dot-product is a special case from matrix multiplication</br>
![image info](./imges/dotProduct_3.png)</br>

- To multiply two matrices the first matrix should have number of columns equals the number of raws of the second one
- The method of calculating the multiplication of two vectors
![image info](./imges/mat_multiplication.png)</br>

<b>Discussion: </br> How matrix maliplication relates to machine learning?